### ISSUE TITLE
Cleaning proteins does not work

### ISSUE THREAD

**Issue by riveros94** [exeResearch/vanddraabe#2]
Dear Emilio, 
When I try to execute 
thrombin10.rcsbCLEANING <- getRCSBdata(prefix="./thrombin10_rawPDBs", resolution=3.0, rFree=NULL, rObserved=NULL, filename=thrombin10.filename)
It says:
Please be patient... Getting PDB information from www.rcsb.org
Error: Not Found

I also tried with another protein and display the same. Can you help me to understand what happened?

Thanks

**Comment by emilioxavier** [comment]
Hi 
Thank you for bringing this to my attention. I hope to have a fix shortly.

Emilio

**Comment by emilioxavier** [comment]
Thank you for your patience.

The problem accessing and downloading RCSB/PBD data resulted from a change in the API mechanism for searching the [RCSB](https://search.rcsb.org/migration-guide.html#legacy-search-api). 

The [bio3d team](http://thegrantlab.org/bio3d/index.html) recently provided a [fix](https://bitbucket.org/Grantlab/bio3d/issues/786/pdbannotate-not-working). The R package is updated (version 2.4-2) and available on [CRAN](https://cran.r-project.org/package=bio3d).

Please let me know if you have any questions.

Thank you again for your patience!
Emilio
